CREATE TABLE REVIEWS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    SENDER_ID INT NOT NULL,
    RECEIVER_ID INT NOT NULL,
    REVIEW VARCHAR NOT NULL,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(id),
    FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(id)
);

